# Best Practices
1. Data preprocessing and cleaning
2. Train test split
3. Apply BOW, TFIDF, Word2Vec
4. Train ML model

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load the data
df = pd.read_csv('Datasets/all_kindle_review.csv')

In [3]:
df.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [4]:
df = df[['rating', 'reviewText']]

In [5]:
df.head()

rating                                         reviewText
0       3  Jace Rankin may be short, but he's nothing to ...
1       5  Great short read.  I didn't want to put it dow...
2       3  I'll start by saying this is the first of four...
3       3  Aggie is Angela Lansbury who carries pocketboo...
4       4  I did not expect this type of book to be in li...

In [6]:
df.shape

(12000, 2)

In [7]:
# Check missing values

df.isnull().sum()

rating        0
reviewText    0
dtype: int64

In [8]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [9]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [10]:
#Preprocessing and cleaning

In [11]:
#Positive and negetive review

In [12]:
df['rating'] = df['rating'].apply(lambda x: 0 if x<3 else 1)

In [13]:
df.head()

rating                                         reviewText
0       1  Jace Rankin may be short, but he's nothing to ...
1       1  Great short read.  I didn't want to put it dow...
2       1  I'll start by saying this is the first of four...
3       1  Aggie is Angela Lansbury who carries pocketboo...
4       1  I did not expect this type of book to be in li...

In [14]:
df.tail()

rating                                         reviewText
11995       1  Valentine cupid is a vampire- Jena and Ian ano...
11996       1  I have read all seven books in this series. Ap...
11997       1  This book really just wasn't my cuppa.  The si...
11998       0  tried to use it to charge my kindle, it didn't...
11999       1  Taking Instruction is a look into the often hi...

In [15]:
df['rating'].unique()

array([1, 0])

In [16]:
# lower all the cases
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from bs4 import BeautifulSoup

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [17]:
df['reviewText'] = df['reviewText'].str.lower()

In [18]:
# Remove special characters
df['reviewText'] = df['reviewText'].apply(lambda x: re.sub('[^a-z A-Z 0-9]+', '', x))
# Remove the stopwords 
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join([y for y in x.split() if y not in stopwords.words('english')]))
#Remove URL
df['reviewText'] = df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '', str(x)))
#Remove html tags
df['reviewText'] = df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
#Remove any additional spaces
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join(x.split()))

In [20]:
df.head()

rating                                         reviewText
0       1  jace rankin may short hes nothing mess man hau...
1       1  great short read didnt want put read one sitti...
2       1  ill start saying first four books wasnt expect...
3       1  aggie angela lansbury carries pocketbooks inst...
4       1  expect type book library pleased find price right

In [21]:
# Apply lemmatization

In [22]:
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()

In [23]:
def leematizeWords(text):\
    return " ".join([lemma.lemmatize(word) for word in text.split()])

In [24]:
df['reviewText'] = df['reviewText'].apply(lambda x: leematizeWords(x))

In [27]:
# Train test split

from sklearn.model_selection import train_test_split

In [28]:
x_train, x_test, y_train, y_test = train_test_split(df['reviewText'], df['rating'], test_size=0.2, random_state=42)

In [29]:
# Apply BOW 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer()

In [30]:
x_train_bow = cv.fit_transform(x_train).toarray()
x_test_bow = cv.transform(x_test).toarray()

In [31]:
x_train_tfidf = tfidf.fit_transform(x_train).toarray()
x_test_tfidf = tfidf.transform(x_test).toarray()

In [32]:
x_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [34]:
# Apply Naive bayes because it works well with sparse metrix dataset
from sklearn.naive_bayes import GaussianNB
nb_bow = GaussianNB().fit(x_train_bow, y_train)
nb_tfidf = GaussianNB().fit(x_train_tfidf, y_train)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [36]:
y_pred_bow = nb_bow.predict(x_test_bow)
y_pred_tfidf = nb_tfidf.predict(x_test_tfidf)

In [37]:
# Print accuracy score

In [38]:
as_bow = accuracy_score(y_pred_bow, y_test)
as_tfidf = accuracy_score(y_pred_tfidf, y_test)

In [39]:
print("BOW Accuracy score: ", as_bow)
print("TFIDF Accuracy score: ", as_tfidf)

BOW Accuracy score:  0.5775
TFIDF Accuracy score:  0.57875


In [40]:
!pip install gensim

  Using cached gensim-4.3.3.tar.gz (23.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): still running...
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached scipy-1.13.1.tar.gz (57.2 MB)
  Installing build dependencies: started
  

  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [47 lines of output]
  + meson setup C:\Users\Asus\AppData\Local\Temp\pip-install-osz5amf0\scipy_032f75c4f197410f9aafd7f1a8aa7b19 C:\Users\Asus\AppData\Local\Temp\pip-install-osz5amf0\scipy_032f75c4f197410f9aafd7f1a8aa7b19\.mesonpy-13mrgqng -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Asus\AppData\Local\Temp\pip-install-osz5amf0\scipy_032f75c4f197410f9aafd7f1a8aa7b19\.mesonpy-13mrgqng\meson-python-native-file.ini
  The Meson build system
  Version: 1.9.0
  Source dir: C:\Users\Asus\AppData\Local\Temp\pip-install-osz5amf0\scipy_032f75c4f197410f9aafd7f1a8aa7b19
  Build dir: C:\Users\Asus\AppData\Local\Temp\pip-install-osz5amf0\scipy_032f75c4f197410f9aafd7f1a8aa7b19\.mesonpy-13mrgqng
  Build type: native build
  Activating VS 17.11.2
  Project name: scipy
  Project version: 1.13.1
  C compiler for the host machine: cl (msvc 19.41.341